### ISSUE TITLE
Show image from url

### ISSUE THREAD

**Issue by maorbenamer** [icanzilb/MTPopupWindow#4]
Hi,
I need help to show an image from a URL in the popup window.
could you please help with the code?

**Comment by icanzilb** [comment]
what have you tried so far?

**Comment by maorbenamer** [comment]
Ive get an image from URL and called it *data.
and then I tried this code:

//show local file
    MTPopupWindow\* winPop = [MTPopupWindow alloc]init];
    UIImage *image = [UIImage imageWithData:data];
    UIColor *c = [UIColor colorWithPatternImage:image];
    winPop.backgroundColor = c;

**Comment by icanzilb** [comment]
I have problems to understand why do you do that ... The popup window meant to show an HTML file - that's why it uses a web view control to show the content. 

Btw - did you try to just pass the URL to the image to showWindowWithHTMLFile: ? I guess if you do that it'll just take the image URL and show it in the web view control.

**Comment by maorbenamer** [comment]
Thanks!

I tried to enter the image URL to showWindowWithHTMLFile: and its work.
but, could i stretch the image to the popup size?

**Comment by icanzilb** [comment]
not automatically
